# Generated by Django 3.1.3 on 2020-11-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('category', models.CharField(choices=[('isAC', 'AC'), ('notAC', 'NON-AC'), ('delux', 'DELUX'), ('single', 'SINGLE'), ('double', 'DOUBLE')], max_length=10)),
                ('beds', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
